<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Moonlight-Front</title>
    <!--------LINK------------>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <!--------LINK------------>
</head>
<body>
   <header>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Moonlight</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
            data-bs-target="#navMenu" 
        aria-controls="navMenu" aria-expanded="false" aria-label="Toggle navigation"> 
        <span class="navbar-toggler-icon" style="filter: invert(1);"></span>
        </button>

        <div class="collapse navbar-collapse" id="navMenu"> 
            <ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
        <?php
        $menuItems = [
            ['name'],
            [''],
            [''],
            [''],
        ];
        ?>

        </div>
        </div>
    </nav>
   </header>
</body>
</html>